# Generated by Django 2.1.4 on 2019-01-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_squashed_0002_poll_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='format_modified',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
