# Generated by Django 2.1.4 on 2019-02-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_auto_20190206_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
    ]
